#ifndef __DEFINES_H
#define __DEFINES_H

#ifndef MD_EXTRA_FIELD
#define MD_EXTRA_FIELD
#endif

#ifndef MD_EXTRA_FIELD_ARRAY
#define MD_EXTRA_FIELD_ARRAY
#endif

#ifndef MD_EXTRA_FIELD_CLIENT
#define MD_EXTRA_FIELD_CLIENT
#endif

#ifndef MD_EXTRA_FIELD_RICH_TEXT
#define MD_EXTRA_FIELD_RICH_TEXT
#endif

#ifndef MD_EXTRA_FIELD_FILE
#define MD_EXTRA_FIELD_FILE
#endif

#ifndef MD_EXTRA_FIELD_FILE_SUBMISSION
#define MD_EXTRA_FIELD_FILE_SUBMISSION
#endif

#ifndef MD_EXTRA_FIELD_TEXT_SUBMISSION
#define MD_EXTRA_FIELD_TEXT_SUBMISSION
#endif

#ifndef MD_EXTRA_FIELD_MOD_ASSIGNMENT_STATUS
#define MD_EXTRA_FIELD_MOD_ASSIGNMENT_STATUS
#endif

#ifndef MD_EXTRA_FIELD_MOD_WORKSHOP_STATUS
#define MD_EXTRA_FIELD_MOD_WORKSHOP_STATUS
#endif

#ifndef MD_EXTRA_FIELD_MOD_ASSIGNMENT
#define MD_EXTRA_FIELD_MOD_ASSIGNMENT
#endif

#ifndef MD_EXTRA_FIELD_MOD_WORKSHOP
#define MD_EXTRA_FIELD_MOD_WORKSHOP
#endif

#ifndef MD_EXTRA_FIELD_MOD_RESOURCE
#define MD_EXTRA_FIELD_MOD_RESOURCE
#endif

#ifndef MD_EXTRA_FIELD_MOD_URL
#define MD_EXTRA_FIELD_MOD_URL
#endif

#ifndef MD_EXTRA_FIELD_MODULE
#define MD_EXTRA_FIELD_MODULE
#endif

#ifndef MD_EXTRA_FIELD_TOPIC
#define MD_EXTRA_FIELD_TOPIC
#endif

#ifndef MD_EXTRA_FIELD_COURSE
#define MD_EXTRA_FIELD_COURSE
#endif

#ifndef MD_EXTRA_FIELD_LOADED_STATUS
#define MD_EXTRA_FIELD_LOADED_STATUS
#endif

#endif